Feature/vdata 6
Sphereon/vdp-internal-did-issuer-resolver pull request #1
Opened 2022-01-21 15:01 UTC by maikel-maas

2022-01-26 13:54 UTC, sksadjad requested changes
Added some remarks. 
please write a manual for testing possibly in readme or someplace else.
based on ticket, separate the postgresql docker-compose file

2022-01-26 13:54 UTC, sksadjad commented on .gitignore
> +temp/
add new line here

2022-01-26 13:54 UTC, sksadjad commented on Dockerfile
> +CMD ["yarn", "start"]
add new line here

2022-01-26 13:54 UTC, sksadjad commented on package.json
> +      "start": "nodemon src/index.ts",
nodemon isn't good for prod usage

2022-01-26 13:54 UTC, sksadjad commented on src/index.ts
> +            console.log(req.url);
remove the print

2022-01-26 13:54 UTC, sksadjad commented on environment.ts
> +export const BASE_URL = '/vdata-agent/v1';
it looks more like a base path

2022-01-26 13:54 UTC, sksadjad commented on environment.ts
> +export const DATABASE = process.env.DATABASE || "vdata";
DB_NAME

2022-01-26 13:54 UTC, sksadjad commented on ormconfig.js
> +}
add new line here

2022-01-26 13:54 UTC, sksadjad commented on src/index.ts
> +            console.log(`App is running at http://localhost:${PORT} in ${ENV} mode`);
logs

2022-01-26 14:05 UTC, maikel-maas commented on ormconfig.js
> +}
Fixed!

2022-01-26 14:07 UTC, maikel-maas commented on environment.ts
> +export const DATABASE = process.env.DATABASE || "vdata";
Fixed!

2022-01-26 14:09 UTC, maikel-maas commented on src/index.ts
> +            console.log(req.url);
I will remove the whole middleware. It doesn't make sense to keep it without the console.log

2022-01-26 14:15 UTC, maikel-maas commented on package.json
> +      "start": "nodemon src/index.ts",
Fixed!

2022-01-26 14:16 UTC, maikel-maas commented on .gitignore
> +temp/
Fixed!

2022-01-28 01:09 UTC, nklomp requested changes
See remarks

2022-01-28 01:09 UTC, nklomp commented on environment.ts
> +export const BASE_PATH = '/vdata-agent/v1';
/vdp-internal-did/v1

2022-01-28 01:09 UTC, nklomp commented on package.json
> +   "name": "@sphereon/vdata_veramo_issuer_resolver",
Please conform to our naming standards, so no underscores. '@sphereon/vdp-internal-did-agent'

2022-01-28 01:09 UTC, nklomp commented on src/agent/agent.ts
> +            ...getUniResolver('did:factom'),
Incorrect. Needs to be 'factom' and 'lto'.

Please look at test cases and documentation for driver/plugin options next time

2022-01-28 01:09 UTC, nklomp commented on src/index.ts
> +            console.log(`App is running at http://localhost:${PORT} in ${ENV} mode`);
Logs are okay for the reasons given. This is a server/docker application running in the cloud

2022-01-28 01:09 UTC, nklomp commented on environment.ts
> +export const DB_NAME = process.env.DB_NAME || "vdata";
vdp-internal-did for the DB name, so that it makes sense if the DB server hosts other databases for the VDP platform

2022-01-28 01:09 UTC, nklomp commented on README.md
> +              defaultKms: 'local'
More options needed. See remark later in the code

2022-01-28 01:09 UTC, nklomp commented on Dockerfile
> +ENV DATABASE="vdata"
vdp-internald-did

2022-01-28 09:07 UTC, maikel-maas commented on Dockerfile
> +ENV DATABASE="vdata"
Fixed!

2022-01-28 09:08 UTC, maikel-maas commented on README.md
> +              defaultKms: 'local'
Ok!

2022-01-28 09:09 UTC, maikel-maas commented on README.md
> +            ...getUniResolver('did:factom'),
Fixed!

2022-01-28 09:09 UTC, maikel-maas commented on environment.ts
> +export const BASE_PATH = '/vdata-agent/v1';
Fixed!

2022-01-28 09:09 UTC, maikel-maas commented on environment.ts
> +export const DB_NAME = process.env.DB_NAME || "vdata";
Fixed!

2022-01-28 09:09 UTC, maikel-maas commented on package.json
> +   "name": "@sphereon/vdata_veramo_issuer_resolver",
Fixed!

2022-01-28 09:10 UTC, maikel-maas commented on src/agent/agent.ts
> +            'did:factom': new FactomDIDProvider({
Fixed!

2022-01-28 09:11 UTC, maikel-maas commented on src/agent/agent.ts
> +            ...getUniResolver('did:factom'),
Fixed!

2022-01-28 10:24 UTC, nklomp approved these changes

2022-01-28 10:40 UTC, merged